package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSocketLog<M extends BaseSocketLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setJson(java.lang.String json) {
		set("json", json);
		return (M)this;
	}
	
	public java.lang.String getJson() {
		return getStr("json");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setCmdid(java.lang.Integer cmdid) {
		set("cmdid", cmdid);
		return (M)this;
	}
	
	public java.lang.Integer getCmdid() {
		return getInt("cmdid");
	}

	public M setCmdcode(java.lang.String cmdcode) {
		set("cmdcode", cmdcode);
		return (M)this;
	}
	
	public java.lang.String getCmdcode() {
		return getStr("cmdcode");
	}

	public M setIsSend(java.lang.Boolean isSend) {
		set("is_send", isSend);
		return (M)this;
	}
	
	public java.lang.Boolean getIsSend() {
		return get("is_send");
	}

}
