package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRobot<M extends BaseRobot<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setBattery(java.lang.Integer battery) {
		set("battery", battery);
		return (M)this;
	}
	
	public java.lang.Integer getBattery() {
		return getInt("battery");
	}

	public M setX(java.lang.Integer x) {
		set("x", x);
		return (M)this;
	}
	
	public java.lang.Integer getX() {
		return getInt("x");
	}

	public M setY(java.lang.Integer y) {
		set("y", y);
		return (M)this;
	}
	
	public java.lang.Integer getY() {
		return getInt("y");
	}

	public M setEnabled(java.lang.Integer enabled) {
		set("enabled", enabled);
		return (M)this;
	}
	
	public java.lang.Integer getEnabled() {
		return getInt("enabled");
	}

	public M setErrorcode(java.lang.Integer errorcode) {
		set("errorcode", errorcode);
		return (M)this;
	}
	
	public java.lang.Integer getErrorcode() {
		return getInt("errorcode");
	}

	public M setWarncode(java.lang.Integer warncode) {
		set("warncode", warncode);
		return (M)this;
	}
	
	public java.lang.Integer getWarncode() {
		return getInt("warncode");
	}

	public M setPause(java.lang.Boolean pause) {
		set("pause", pause);
		return (M)this;
	}
	
	public java.lang.Boolean getPause() {
		return get("pause");
	}

}
