package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActionLog<M extends BaseActionLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public M setAction(java.lang.String action) {
		set("action", action);
		return (M)this;
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}

	public M setTime(java.lang.Long time) {
		set("time", time);
		return (M)this;
	}
	
	public java.lang.Long getTime() {
		return getLong("time");
	}

	public M setTimeString(java.util.Date timeString) {
		set("timeString", timeString);
		return (M)this;
	}
	
	public java.util.Date getTimeString() {
		return get("timeString");
	}

}
