package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseErrorLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ErrorLog extends BaseErrorLog<ErrorLog> {
	public static final ErrorLog dao = new ErrorLog().dao();
}
