package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseMaterialType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialType extends BaseMaterialType<MaterialType> {
	public static final MaterialType dao = new MaterialType().dao();
}
