package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Material extends BaseMaterial<Material> {
	public static final Material dao = new Material().dao();
}
