package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BasePackingListItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PackingListItem extends BasePackingListItem<PackingListItem> {
	public static final PackingListItem dao = new PackingListItem().dao();
}
