package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BasePositionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PositionLog extends BasePositionLog<PositionLog> {
	public static final PositionLog dao = new PositionLog().dao();
}
