package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseRobot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Robot extends BaseRobot<Robot> {
	public static final Robot dao = new Robot().dao();
}
