package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseSocketLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SocketLog extends BaseSocketLog<SocketLog> {
	public static final SocketLog dao = new SocketLog().dao();
}
