package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskLog extends BaseTaskLog<TaskLog> {
	public static final TaskLog dao = new TaskLog().dao();
}
