package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseUserType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserType extends BaseUserType<UserType> {
	public static final UserType dao = new UserType().dao();
}
