package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseWindow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Window extends BaseWindow<Window> {
	public static final Window dao = new Window().dao();
}
